export const categories = {
  all: { label: 'Все категории', accent: 'var(--accent)' },
  nature: { label: 'Природа', accent: '#34d399' },
  city: { label: 'Город', accent: '#60a5fa' },
  food: { label: 'Еда', accent: '#f59e0b' },
  travel: { label: 'Путешествия', accent: '#22d3ee' },
  art: { label: 'Искусство', accent: '#c084fc' },
};

export const tags = {
  sunset: { label: 'Закат' },
  forest: { label: 'Лес' },
  mountains: { label: 'Горы' },
  water: { label: 'Вода' },
  minimal: { label: 'Минимализм' },
  neon: { label: 'Неон' },
  architecture: { label: 'Архитектура' },
  dessert: { label: 'Десерт' },
  coffee: { label: 'Кофе' },
  street: { label: 'Улица' },
  museum: { label: 'Музей' },
  portrait: { label: 'Портрет' },
  texture: { label: 'Текстура' },
  sea: { label: 'Море' },
  vintage: { label: 'Винтаж' },
};

export const sortOptions = {
  featured: { label: 'По умолчанию' },
  titleAsc: { label: 'Название: А → Я' },
  titleDesc: { label: 'Название: Я → А' },
  category: { label: 'Сначала по категории' },
};

export const galleryItems = [
  {
    id: 'aurora-valley',
    title: 'Aurora Valley',
    description:
      'Холодная панорама горного озера с отражением света, чистой водой и ощущением большого пространства.',
    category: 'nature',
    tags: ['mountains', 'sunset', 'water'],
    alt: 'Горное озеро с отражением скал и солнечными лучами.',
    image: './assets/images/aurora-valley.webp',
    credit: 'Pexels · eberhardgross',
    order: 1,
  },
  {
    id: 'moss-forest',
    title: 'Moss Forest',
    description:
      'Лесная сцена с густой тенью, мшистыми камнями и спокойной природной фактурой.',
    category: 'nature',
    tags: ['forest', 'water', 'texture'],
    alt: 'Мшистый лес с камнями и плотными деревьями.',
    image: './assets/images/moss-forest.webp',
    credit: 'Pexels · septimiu lupea',
    order: 2,
  },
  {
    id: 'coastal-breeze',
    title: 'Coastal Breeze',
    description:
      'Спокойный морской кадр с открытым горизонтом, мягким светом и ощущением путешествия.',
    category: 'travel',
    tags: ['sea', 'minimal', 'sunset'],
    alt: 'Спокойное море с лодкой у горизонта.',
    image: './assets/images/coastal-breeze.webp',
    credit: 'Pexels · malcolnphoto',
    order: 3,
  },
  {
    id: 'metro-neon',
    title: 'Metro Neon',
    description:
      'Ночной городской ритм, насыщенный вывесками, тёплыми отражениями и живой уличной атмосферой.',
    category: 'city',
    tags: ['neon', 'street', 'architecture'],
    alt: 'Ночная улица мегаполиса с неоновыми вывесками.',
    image: './assets/images/metro-neon.webp',
    credit: 'Pexels · apasaric',
    order: 4,
  },
  {
    id: 'glass-atrium',
    title: 'Glass Atrium',
    description:
      'Современная общественная архитектура со сложной геометрией, стеклом и выразительным ритмом конструкций.',
    category: 'city',
    tags: ['architecture', 'minimal', 'street'],
    alt: 'Современный стеклянный атриум со сложной геометрией.',
    image: './assets/images/glass-atrium.webp',
    credit: 'Pexels · blackcurrant great',
    order: 5,
  },
  {
    id: 'rooftop-lines',
    title: 'Rooftop Lines',
    description:
      'Графичный архитектурный ракурс с лаконичной пластикой фасада, чистыми линиями и холодной палитрой.',
    category: 'city',
    tags: ['architecture', 'minimal', 'vintage'],
    alt: 'Минималистичная городская архитектура с чистыми линиями.',
    image: './assets/images/rooftop-lines.webp',
    credit: 'Pexels · stephentcandrews',
    order: 6,
  },
  {
    id: 'citrus-tart',
    title: 'Citrus Tart',
    description:
      'Аккуратная десертная подача с ярким акцентом цвета, чистой формой и ресторанной стилистикой.',
    category: 'food',
    tags: ['dessert', 'minimal', 'texture'],
    alt: 'Десерт на тарелке с ягодами и ярким соусом.',
    image: './assets/images/citrus-tart.webp',
    credit: 'Pexels · valeriya',
    order: 7,
  },
  {
    id: 'morning-espresso',
    title: 'Morning Espresso',
    description:
      'Тёплый кофейный кадр с древесной фактурой, мягким светом и выразительной пенкой латте.',
    category: 'food',
    tags: ['coffee', 'minimal', 'vintage'],
    alt: 'Кофейная чашка на деревянном столе.',
    image: './assets/images/morning-espresso.webp',
    credit: 'Pexels · olenkabohovyk',
    order: 8,
  },
  {
    id: 'bakery-window',
    title: 'Bakery Window',
    description:
      'Уличная витрина с выпечкой, отражениями и живым ощущением локальной пекарни.',
    category: 'food',
    tags: ['dessert', 'street', 'coffee'],
    alt: 'Витрина пекарни с булочками, сэндвичами и выпечкой.',
    image: './assets/images/bakery-window.webp',
    credit: 'Pexels · birseydaha',
    order: 9,
  },
  {
    id: 'desert-road',
    title: 'Desert Road',
    description:
      'Маршрут через открытый ландшафт с длинной перспективой, сухой палитрой и ощущением свободы.',
    category: 'travel',
    tags: ['mountains', 'minimal', 'vintage'],
    alt: 'Дорога через пустынный пейзаж.',
    image: './assets/images/desert-road.webp',
    credit: 'Pexels · jplenio',
    order: 10,
  },
  {
    id: 'harbor-night',
    title: 'Harbor Night',
    description:
      'Ночной городской берег с отражениями на воде, световыми дорожками и атмосферой большого порта.',
    category: 'travel',
    tags: ['sea', 'water', 'neon'],
    alt: 'Ночной городской берег с отражениями света в воде.',
    image: './assets/images/harbor-night.webp',
    credit: 'Pexels · Pixabay',
    order: 11,
  },
  {
    id: 'gallery-face',
    title: 'Gallery Face',
    description:
      'Портретная сцена в художественном пространстве с тёплым светом и музейной атмосферой.',
    category: 'art',
    tags: ['portrait', 'museum', 'texture'],
    alt: 'Портретная сцена в художественной галерее.',
    image: './assets/images/gallery-face.webp',
    credit: 'Pexels · victoria kibaki',
    order: 12,
  },
  {
    id: 'marble-study',
    title: 'Marble Study',
    description:
      'Классическая пластика, музейный свет и внимание к материалу, объёму и декоративной фактуре.',
    category: 'art',
    tags: ['museum', 'minimal', 'texture'],
    alt: 'Мраморная скульптура в художественной композиции.',
    image: './assets/images/marble-study.webp',
    credit: 'Pexels · bilgekutukoglu',
    order: 13,
  },
  {
    id: 'poster-room',
    title: 'Poster Room',
    description:
      'Интерьер с коллекцией постеров и фотографий, собранных в цельную визуальную композицию.',
    category: 'art',
    tags: ['minimal', 'portrait', 'vintage'],
    alt: 'Интерьер с постерами и фотографиями на стене.',
    image: './assets/images/poster-room.webp',
    credit: 'Pexels · cottonbro',
    order: 14,
  },
  {
    id: 'rain-station',
    title: 'Rain Station',
    description:
      'Дождливая городская сцена с зонтами, неоном и кинематографичной глубиной ночного кадра.',
    category: 'city',
    tags: ['street', 'water', 'neon'],
    alt: 'Дождливая неоновая улица большого города.',
    image: './assets/images/rain-station.webp',
    credit: 'Pexels · agk42',
    order: 15,
  },
];
